[package]
name = "wat-ast"
version = "0.1.0"
authors = ["Yage Hu <yagejhu@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "WebAssembly text format (.wat) abstract syntax tree for generating human readable code."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
