edition = "2018"

combine_control_expr = false
enum_discrim_align_threshold = 20
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
max_width = 80
merge_imports = true
struct_field_align_threshold = 20
unstable_features = true
wrap_comments = true
